[33mcommit 785b3184b9f38a37907acd19bad834cf6699f137[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mmain[m[33m, [m[1;31morigin/main[m[33m, [m[1;31morigin/HEAD[m[33m)[m
Author: Jason Dean <jasondeanfitness@outlook.com>
Date:   Mon Aug 25 22:27:40 2025 +0100

    fix: implement Clerk Billing, fix fonts, add all dependencies

convex-dashboard2/(landing)/animated-list-custom.tsx
convex-dashboard2/(landing)/call-to-action.tsx
convex-dashboard2/(landing)/cpu-architecture.tsx
convex-dashboard2/(landing)/faqs.tsx
convex-dashboard2/(landing)/features-one.tsx
convex-dashboard2/(landing)/footer.tsx
convex-dashboard2/(landing)/header.tsx
convex-dashboard2/(landing)/hero-section.tsx
convex-dashboard2/(landing)/how-to-book.tsx
convex-dashboard2/(landing)/page.tsx
convex-dashboard2/(landing)/table.tsx
convex-dashboard2/(landing)/testimonials.tsx
convex-dashboard2/admin-dashboard/app-sidebar.tsx
convex-dashboard2/admin-dashboard/chart-area-interactive.tsx
convex-dashboard2/admin-dashboard/compliance/page.tsx
convex-dashboard2/admin-dashboard/data-table.tsx
convex-dashboard2/admin-dashboard/data.json
convex-dashboard2/admin-dashboard/layout.tsx
convex-dashboard2/admin-dashboard/loading-bar.tsx
convex-dashboard2/admin-dashboard/logs/page.tsx
convex-dashboard2/admin-dashboard/manual-actions/page.tsx
convex-dashboard2/admin-dashboard/nav-documents.tsx
convex-dashboard2/admin-dashboard/nav-main.tsx
convex-dashboard2/admin-dashboard/nav-secondary.tsx
convex-dashboard2/admin-dashboard/nav-user.tsx
convex-dashboard2/admin-dashboard/page.tsx
convex-dashboard2/admin-dashboard/payment-gated/page.tsx
convex-dashboard2/admin-dashboard/payments/page.tsx
convex-dashboard2/admin-dashboard/quotes/page.tsx
convex-dashboard2/admin-dashboard/section-cards.tsx
convex-dashboard2/admin-dashboard/settings/page.tsx
convex-dashboard2/admin-dashboard/shipments/page.tsx
convex-dashboard2/admin-dashboard/site-header.tsx
convex-dashboard2/admin-dashboard/support/page.tsx
convex-dashboard2/admin-dashboard/tools/testing/page.tsx
convex-dashboard2/admin-dashboard/users/page.tsx
convex-dashboard2/api/admin/stats/route.ts
convex-dashboard2/api/bookings/route.ts
convex-dashboard2/api/documents/route.ts
convex-dashboard2/api/docusign/callback/route.ts
convex-dashboard2/api/docusign/debug/route.ts
convex-dashboard2/api/docusign/envelope/route.ts
convex-dashboard2/api/docusign/status/route_fixed.ts
convex-dashboard2/api/e2e/run/route.ts
convex-dashboard2/api/geo/route/route.ts
convex-dashboard2/api/instant-quote-booking/route.ts
convex-dashboard2/api/quotes/route.ts
convex-dashboard2/api/rates/route.ts
convex-dashboard2/api/shipments/[id]/tracking/route.ts
convex-dashboard2/components/ConvexClientProvider.tsx
convex-dashboard2/components/assistant/chat-bar.tsx
convex-dashboard2/components/custom-clerk-pricing.tsx
convex-dashboard2/components/enterprise/AdvancedDataTable.tsx
convex-dashboard2/components/enterprise/CommandPalette.tsx
convex-dashboard2/components/enterprise/EnterpriseCard.tsx
convex-dashboard2/components/enterprise/EnterpriseHero.tsx
convex-dashboard2/components/enterprise/FreightDashboard.tsx
convex-dashboard2/components/kokonutui/attract-button.tsx
convex-dashboard2/components/logo.tsx
convex-dashboard2/components/magicui/animated-list.tsx
convex-dashboard2/components/magicui/pulsating-button.tsx
convex-dashboard2/components/mode-toggle.tsx
convex-dashboard2/components/motion-primitives/infinite-slider.tsx
convex-dashboard2/components/motion-primitives/progressive-blur.tsx
convex-dashboard2/components/react-bits/pixel-card.tsx
convex-dashboard2/components/react-bits/splash-cursor.tsx
convex-dashboard2/components/react-bits/text-cursor.tsx
convex-dashboard2/components/theme-provider.tsx
convex-dashboard2/components/tracking/MapContainerComponent.tsx
convex-dashboard2/components/tracking/ShipmentMap.tsx
convex-dashboard2/components/tracking/ShipmentMapInner.tsx
convex-dashboard2/components/tracking/ShipmentMapWrapper.tsx
convex-dashboard2/components/tracking/TrackingProgress.tsx
convex-dashboard2/components/ui/animated-group.tsx
convex-dashboard2/components/ui/avatar.tsx
convex-dashboard2/components/ui/badge.tsx
convex-dashboard2/components/ui/breadcrumb.tsx
convex-dashboard2/components/ui/button.tsx
convex-dashboard2/components/ui/card.tsx
convex-dashboard2/components/ui/chart.tsx
convex-dashboard2/components/ui/checkbox.tsx
convex-dashboard2/components/ui/dialog.tsx
convex-dashboard2/components/ui/drawer.tsx
convex-dashboard2/components/ui/dropdown-menu.tsx
convex-dashboard2/components/ui/input.tsx
convex-dashboard2/components/ui/label.tsx
convex-dashboard2/components/ui/select.tsx
convex-dashboard2/components/ui/separator.tsx
convex-dashboard2/components/ui/sheet.tsx
convex-dashboard2/components/ui/sidebar.tsx
convex-dashboard2/components/ui/skeleton.tsx
convex-dashboard2/components/ui/sonner.tsx
convex-dashboard2/components/ui/switch.tsx
convex-dashboard2/components/ui/table.tsx
convex-dashboard2/components/ui/tabs.tsx
convex-dashboard2/components/ui/text-effect.tsx
convex-dashboard2/components/ui/toggle-group.tsx
convex-dashboard2/components/ui/toggle.tsx
convex-dashboard2/components/ui/tooltip.tsx
convex-dashboard2/convex/README.md
convex-dashboard2/convex/_generated/api.d.ts
convex-dashboard2/convex/_generated/api.js
convex-dashboard2/convex/_generated/dataModel.d.ts
convex-dashboard2/convex/_generated/server.d.ts
convex-dashboard2/convex/_generated/server.js
convex-dashboard2/convex/auth.config.ts
convex-dashboard2/convex/bookings.ts
convex-dashboard2/convex/clerk-webhook-events-catalog.md
convex-dashboard2/convex/documents.ts
convex-dashboard2/convex/geo.ts
convex-dashboard2/convex/http.ts
convex-dashboard2/convex/paymentAttemptTypes.ts
convex-dashboard2/convex/paymentAttempts.ts
convex-dashboard2/convex/quotes.ts
convex-dashboard2/convex/schema.ts
convex-dashboard2/convex/shipments.ts
convex-dashboard2/convex/tsconfig.json
convex-dashboard2/convex/users.ts
convex-dashboard2/favicon.ico
convex-dashboard2/globals.css
convex-dashboard2/layout.tsx
convex-dashboard2/not-found.tsx
convex-dashboard2/package.json
convex-dashboard2/user/accounts/page.tsx
convex-dashboard2/user/app-sidebar.tsx
convex-dashboard2/user/bookings/page.tsx
convex-dashboard2/user/compliance/page.tsx
convex-dashboard2/user/documents/[id]/page.tsx
convex-dashboard2/user/documents/page.tsx
convex-dashboard2/user/enterprise-dashboard.tsx
convex-dashboard2/user/layout.tsx
convex-dashboard2/user/page.tsx
convex-dashboard2/user/payments/page.tsx
convex-dashboard2/user/quotes/page.tsx
convex-dashboard2/user/reports/page.tsx
convex-dashboard2/user/shipments/page.tsx
convex-dashboard2/user/site-header.tsx
convex-dashboard2/user/testing/page.tsx
